# ===== PROFILE =====
# Local development is the default. Render should set SPRING_PROFILES_ACTIVE=prod.
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.config.import=optional:file:.env[.properties]

# ===== SERVER =====
server.port=${PORT}

# ===== COMMON JPA =====
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===== COMMON JWT =====
app.jwt.expiration=${JWT_EXPIRATION}

# ===== COMMON OPENAPI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
